### ISSUE TITLE
SEGFAULT loading met data with time-varying RHw

### ISSUE THREAD

**Issue by trdean1** [MIT-LAE/APCEMM#3]
I am trying to load a met data file that has a RH values for 24 time steps and 28 altitude steps.  This causes APCEMM to throw a segfault.  I dug into the issue a little bit and found that the segfault occurs at line 440 of Meteorology.cpp.

Here is the code in question starting at [line 433](https://github.com/MIT-LAE/APCEMM/blob/main/Code.v05-00/src/Core/Meteorology.cpp#L433):
```
//Assumes constant RHw for the entire domain

/* Define temperature input dimension */
NcVar relhumid_ncVar = dataFile.getVar("relative_humidity");
relhumid_ncVar.getVar(relhumid_init);

/* Identify temperature at above pressure */
RHw_user = relhumid_init[i_Zp];
```

The issue is that `relhumid_init` is an array that is of length `altitudeDim`. When `relhumid_ncVar.getVar` gets called, it writes 24*28 floats to `relhumid_init` because of the size of the RH values stored in the data being loaded.  This clobbers a bunch of variables including `i_Zp` which causes the segfault on line 440.

Is there any way to run APCEMM in a way that accounts for changing RH values or does the met data need to be contained to only having data from a single time?  If the later is true you may wish to check the dimensions of the met data and raise an error here rather than allowing the code to segfault.

**Comment by sdeastham** [comment]
Hi @trdean1 ! We do have a patch (somewhere) which allows the RH field to have multiple time entries - however, the later ones are not used. I'll follow up to try and get this patch in place soon, likely alongside some other improvements which we have been making.

The reason we don't update RH is that we are explicitly tracking water mass in the contrail air. Updating the relative humidity directly without modeling mixing would mean that we are non-physically adding/destroying water mass. That being said, this is an open area of debate because we _do_ want to account for the mixing-in of ambient air as the contrail air mass travels. For the moment we do allow temperature to update over time if the user requests it (which raises interesting questions in itself) and are working on a way to explore physically-consistent mechanisms for ambient air (including heat and water) to mix with the contrail air mass.

**Comment by trdean1** [comment]
Awesome, thanks Seb!  For context I am working to make some sort of interface between our [pycontrails](https://github.com/contrailcirrus/pycontrails) repository and your model. This will likely just be a way to export flight/engine information along with met data out of our library and into a format that can be read by the APCEMM executable. For now I will just export a single time-step worth of RH data.

**Comment by sdeastham** [comment]
@trdean1 - can you confirm that this is no longer an issue? Time-varying RH is working in our tests (modifications being imposed at the boundaries), so I'm keen to either close this issue or to find and fix the bug that you are encountering.

**Comment by trdean1** [comment]
Hi @sdeastham - I managed to rebuild with the latest release and it does appear the issue is solved.  Thanks!
